#!/usr/bin/env python3
"""Orchestrate a teaching video from a single topic.

Pipeline (deterministic parts handled here, loop-skilled diagrams done interactively):
  topic -> teaching script (teacher voice) -> split into scenes
        -> TTS per scene via kokoro-tts-production (hm_omega, speed 0.9)
        -> build manifest.json for build_video.py

The SVG->PNG diagram generation is done per-scene by the loop skill (interactive,
visual judging) and produces PNGs named sceneNN.png alongside each audio file.

Usage:
    orchestrate.py "Kubernetes" [--voice hm_omega] [--speed 0.9]
                [--out-dir DIR] [--workdir WORKDIR]

Outputs (in --workdir):
    script.md          full teaching script with scene markers
    manifest.json      for build_video.py (audio + image paths)
    audio/sceneNN.mp3  per-scene narration
    images/sceneNN.png per-scene diagram (must be generated by loop skill)
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys


TTS = "/Users/manjunathkanavi/.hermes/skills/kokoro-tts-production/scripts/kokoro_tts.py"
BUILD_VIDEO = "/Users/manjunathkanavi/.hermes/skills/tech_teacher/scripts/build_video.py"


def run(cmd: list[str], label: str = "", input_data: bytes | None = None) -> subprocess.CompletedProcess:
    proc = subprocess.run(cmd, capture_output=True, input=input_data)
    if label:
        print(f"[{label}] exit={proc.returncode}")
        if proc.stderr.strip() and proc.returncode != 0:
            sys.stderr.write(proc.stderr.decode("utf-8", "replace"))
    return proc


def generate_tts(scene_text: str, out_path: str, voice: str, speed: float) -> None:
    """Synthesize one scene's audio via the production kokoro TTS skill.

    Retries transient gateway errors (HTTP 502/504) with exponential backoff,
    since bursting many concurrent requests can overload the TTS replicas.
    """
    import time

    max_attempts = 6
    last_err: str | None = None
    for attempt in range(1, max_attempts + 1):
        proc = run(
            ["python3", TTS, "--stdin", "-v", voice, "-s", str(speed), "-o", out_path],
            label=f"TTS {os.path.basename(out_path)} (attempt {attempt})",
            input_data=scene_text.encode("utf-8"),
        )
        if proc.returncode == 0:
            return
        last_err = (proc.stderr or b"").decode("utf-8", "replace").strip()
        # Only retry on transient gateway errors; fail fast otherwise.
        if "429" in last_err:
            # Rate limit (Too Many Requests): back off to the API window (~30s)
            # so concurrent requests stagger instead of hammering at once.
            backoff = 30 * (attempt - 1) + 5
        elif "502" not in last_err and "504" not in last_err:
            if proc.stderr.strip():
                sys.stderr.write(proc.stderr.decode("utf-8", "replace"))
            raise RuntimeError(f"TTS failed: {last_err}")
        else:
            backoff = 2 ** (attempt - 1) * 3
        print(f"[warn] TTS {os.path.basename(out_path)}: "
              f"{last_err.splitlines()[-1] if last_err else 'error'} "
              f"(attempt {attempt}/{max_attempts}); retrying in {backoff}s", flush=True)
        time.sleep(backoff)
    raise RuntimeError(f"TTS still failing after {max_attempts} attempts: {last_err}")


def split_into_scenes(script_text: str) -> list[dict]:
    """Split the teaching script into scenes on '## Scene' markers.

    Returns list of {"title": ..., "text": ...} preserving scene order and
    numbering from the marker. Falls back to paragraph splitting if no markers.
    """
    lines = script_text.splitlines()
    scenes: list[dict] = []
    current_title: str | None = None
    current_lines: list[str] = []

    def flush() -> None:
        nonlocal current_title, current_lines
        body = "\n".join(l.strip() for l in current_lines if l.strip()).strip()
        body = re.sub(r"\s+", " ", body)
        # Only emit a scene if there is real body text (ignore stray heading lines).
        if current_lines and not any(l.strip().startswith("#") for l in current_lines):
            scenes.append({"title": current_title or f"Scene {len(scenes)+1}", "text": body})
        current_lines = []

    for line in lines:
        m = re.match(r"##\s+(?:Scene\s+\d+[:\-]?\s*)?(.+)", line.strip())
        if m:
            flush()
            current_title = m.group(1).strip()
        elif line.strip().startswith("#"):
            # First-level markdown heading — ignore entirely.
            continue
        elif line.strip():
            current_lines.append(line)
    flush()

    if not scenes:
        # Fallback: split on blank-line-separated paragraphs.
        blocks = re.split(r"\n\s*\n", script_text.strip())
        for i, block in enumerate(blocks):
            text = re.sub(r"\s+", " ", block.strip())
            if text:
                scenes.append({"title": f"Section {i+1}", "text": text})

    return scenes


def build_manifest(workdir: str, scenes: list[dict]) -> None:
    """Write manifest.json mapping each scene to its audio + image."""
    out = os.path.join(workdir, "final.mp4")
    scenes_manifest = []
    for i, scene in enumerate(scenes, start=1):
        audio = os.path.join(workdir, "audio", f"scene{i:02d}.mp3")
        image = os.path.join(workdir, "images", f"scene{i:02d}.png")
        scenes_manifest.append({
            "audio": audio,
            "image": image if os.path.exists(image) else None,
            "title": scene["title"],
        })
    manifest = {"out": out, "scenes": scenes_manifest}
    with open(os.path.join(workdir, "manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2)


def main() -> None:
    ap = argparse.ArgumentParser(description="Orchestrate a teaching video from a topic.")
    ap.add_argument("topic", help="The tech topic to teach")
    ap.add_argument("--voice", default="hm_omega", help="Kokoro voice id (default hm_omega)")
    ap.add_argument("--speed", type=float, default=0.9, help="Speech speed (default 0.9)")
    ap.add_argument("--parallel", type=int, default=5, help="Max concurrent kokoro TTS replicas (default 5). Transient gateway errors are retried with backoff.")
    ap.add_argument("--out-dir", default=None, help="Base output directory")
    ap.add_argument("--workdir", default=None, help="Work dir (default: <out-dir>/<topic>)")
    args = ap.parse_args()

    out_dir = args.out_dir or os.path.join(os.getcwd(), "tech_teacher")
    workdir = args.workdir or os.path.join(out_dir, re.sub(r"[^a-z0-9]+", "_", args.topic.lower()))
    os.makedirs(os.path.join(workdir, "audio"), exist_ok=True)
    os.makedirs(os.path.join(workdir, "images"), exist_ok=True)

    print(f"[setup] workdir={workdir}")
    print(f"[setup] voice={args.voice} speed={args.speed}")

    # --- STEP 1: teaching script (generated by loop skill / interactive) ---
    print("[step] Generating teaching script for: " + args.topic)
    # The loop skill produces this file. Placeholder marker so orchestration can proceed.
    script_path = os.path.join(workdir, "script.md")
    if not os.path.exists(script_path):
        with open(script_path, "w") as f:
            f.write(f"# {args.topic}\n\n(Generate this via the loop skill, then re-run orchestrate.py)\n")
        print("[warn] script.md missing — generate it via the loop skill first.")

    with open(script_path) as f:
        script_text = f.read()

    # --- STEP 2: split into scenes ---
    scenes = split_into_scenes(script_text)
    print(f"[step] {len(scenes)} scene(s): " + ", ".join(s['title'] for s in scenes))

    # --- STEP 3: TTS per scene (skip if audio already exists) ---
    # Generate scenes in parallel across up to --parallel kokoro replicas so the
    # per-call SSH key fetch and API latency overlap instead of running one at a time.
    remaining = []
    for i, scene in enumerate(scenes, start=1):
        audio_path = os.path.join(workdir, "audio", f"scene{i:02d}.mp3")
        if os.path.exists(audio_path) and os.path.getsize(audio_path) > 0:
            print(f"[skip] audio scene{i:02d} already exists")
        else:
            remaining.append((i, scene["text"], audio_path))

    def _one(item):
        i, text, audio_path = item
        generate_tts(text, audio_path, args.voice, args.speed)

    if remaining:
        workers = max(1, min(args.parallel, len(remaining)))
        print(f"[step] TTS {len(remaining)} scene(s) with up to {workers} concurrent kokoro replicas…")
        from concurrent.futures import ThreadPoolExecutor, as_completed
        with ThreadPoolExecutor(max_workers=workers) as ex:
            futures = {ex.submit(_one, r): r for r in remaining}
            done = 0
            for fut in as_completed(futures):
                done += 1
                try:
                    fut.result()
                except Exception as exc:  # noqa: BLE001
                    print(f"[ERROR] scene generation failed: {exc}", file=sys.stderr)
                print(f"  [{done}/{len(remaining)}] scene audio done", flush=True)

    # --- STEP 4: build manifest (images filled by loop skill as PNGs) ---
    build_manifest(workdir, scenes)

    print(f"[done] Manifest ready at {os.path.join(workdir, 'manifest.json')}")
    print("[next] Run: python3 " + BUILD_VIDEO + f' {os.path.join(workdir, "manifest.json")} --outdir {out_dir} --width 1920 --height 1080')


if __name__ == "__main__":
    main()
