#!/usr/bin/env python3
"""cinematographer — offline, language-agnostic scene breakdown and 5-second video-prompt generator.

Takes natural-language text in ANY language (English, Kannada, Hindi, ...) and turns it into a
scene-by-scene breakdown plus ready-to-use 5-second video-generation prompts.

Two modes:

  MODE A — plot → structured plan (movie-maker integration).
    The AGENT performs the semantic planning pass in-model: it reads a plot and emits a structured
    plan (theme, characters with bibles, beats where each 5s scene attributes who says what).
    This script then assembles that plan deterministically into scenes.json with:

      * canonical subjects (from character identities, NOT sentence-split heuristics)
        — fixes the "auto scene-breaker is broken" bug where subjects became fragments like
          "Terrified, the animals agreed".
      * per-scene dialogue attribution ("who says what") — carried verbatim from the plan.
      * character consistency — every scene reuses ONE canonical Pixar-look prompt + fixed seed per
        character (generated by characters.py via disney-character-creator), so faces/hair/wardrobe
        don't drift shot-to-shot.
      * real continuity — a genuine shared visual_contract_id, computed carried palette/lighting that
        varies by emotion only, and actual 180°/30°/eyeline/matching-action shot rules.
      * Pixar-look video prompt — fixed schema + shared style-lock block appended identically to
        every scene, plus a per-beat model recommendation.

  MODE B — plain text (backward compatible).
    A single narration-only scene per sentence block. Kept for standalone use; the planner +
    character-consistency path (Mode A) is preferred.

No external LLM, no network — fully offline. The semantic understanding lives in the agent that
runs this skill; every function below is deterministic Python.

Usage:
    # Mode A — structured plan (movie-maker calls this)
    python3 main.py --plan path/to/plan.json [--max-scenes 12]

    # Mode B — plain text (backward compatible)
    python3 main.py --text "A woman walks into a rain-soaked alley."
    python3 main.py --file path/to/story.txt [--style cinematic] [--aspect 16:9]
"""

import argparse
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

# Resolve sibling modules (symlink-safe) and disney-character-creator.
THIS_SKILL = Path(__file__).resolve().parent.parent  # .../skills/cinematographer
SKILLS_ROOT = THIS_SKILL.parent

sys.path.insert(0, str(Path(__file__).resolve().parent / "scripts"))  # scripts/
from scene_assembly import assemble_scenes  # noqa: E402

try:
    from planner import build_plan_from_plot, write_plan  # noqa: E402
except Exception:  # pragma: no cover - planner always ships alongside main.py
    build_plan_from_plot = None
    write_plan = None

# ─── Backward-compat presets (used only by Mode B plain-text path) ──────────
SCENE_CHANGE_PATTERNS = [
    r"\bthen\b", r"\band then\b", r"\bafter that\b", r"\bfinally\b",
    r"\bmeanwhile\b", r"\bsubsequently\b", r"\blater\b",
    r"\bmeanwhile\b", r"\bin the meantime\b", r"\bjust then\b",
    r"\bafter (a|the) ", r"\byears? later\b", r"\bdays? later\b",
    r"\bminutes? later\b", r"\bmoments? later\b", r"\bhours? later\b",
]

DEFAULT_NEGATIVE = ("blurry, low quality, deformed hands or faces, extra limbs,"
                    " jittery motion, glitching artifacts, strobing lights, "
                    "text overlays, watermark")


def _slugify_title(text: str) -> str:
    slug = re.sub(r"[^\w\s-]", "", text, flags=re.UNICODE)
    slug = re.sub(r"[\s_]+", "-", slug.strip())[:50]
    return slug or "untitled_scene_breakdown"


# ─── Mode B — plain-text scene assembly (backward compatible) ──────────────
def _assemble_plain_text(text: str, max_scenes: int) -> dict:
    """Build scenes from plain narration text (Mode B, no characters/dialogue)."""
    # Split into beats by sentence boundaries; keep it simple for standalone use.
    sentences = re.split(r"(?<=[.!?])\s+", text.strip())
    sentences = [s for s in sentences if s.strip()]

    scenes = []
    prev_emotion = ""
    vc_id = f"vc-plain-{abs(hash(text[:60])) % 1000}"
    for idx, sent in enumerate(sentences[:max_scenes]):
        low = sent.lower()
        emotion = "neutral"
        for kw, tgt in [("terrified", "haunting, dread-filled"), ("fear", "tense, anxious"),
                         ("happy", "uplifting, joyful"), ("sad", "melancholic, somber"),
                         ("brave", "determined, resolute"), ("love", "warm, tender")]:
            if kw in low:
                emotion = tgt
                break

        subject = " ".join(sent.split()[:3]).strip(".,;:") or f"Scene {idx + 1}"
        visual_desc = (f"{subject} — mood: {emotion}")

        vp = (f"Subject: {subject}. "
              f"Mood: {emotion.strip()}. slow push-in camera movement. Lighting: balanced "
              f"cinematic lighting. Aspect ratio cinematic widescreen aspect ratio 16:9. "
              f"Single continuous 5-second shot at 24fps. Style lock: octane render, subsurface "
              f"scattering, warm volumetric lighting, cinematic depth of field, clean soft "
              f"shadows, studio quality 3D render, Pixar-style 3D animation "
              f"[negative: {DEFAULT_NEGATIVE}]")

        carried = ["emotional_target"] if idx > 0 else []
        scenes.append({
            "scene_number": idx + 1,
            "title": subject[:40],
            "beat_type": "setup" if idx == 0 else "advance plot",
            "characters_present": [],
            "dialogue": [],
            "narration": sent.strip(),
            "visual_description": visual_desc,
            "continuity": {
                "visual_contract_id": vc_id,
                "shot_rule": "establishing shot" if idx == 0 else "30-degree camera shift to avoid jump cut",
                "carried_over": carried,
            },
            "cinematography": {
                "camera": "slow push-in",
                "lens": "35mm",
                "lighting": "balanced cinematic lighting",
                "color_palette": "balanced natural tones",
                "composition": "rule of thirds",
                "mood": emotion,
            },
            "video_prompt": vp,
            "negative_prompt": DEFAULT_NEGATIVE,
            "motion_params": {"motion_strength": 0.7, "duration_sec": 5},
            "model_recommendation": "Sora 2 Pro",
            "characters_present_prompts": {},
            "setting": "",
            "seed": None,
        })
        prev_emotion = emotion if emotion != "neutral" else prev_emotion

    return {
        "theme": "",
        "title": _slugify_title(text[:50]),
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "generator": "cinematographer (offline plain-text assembly)",
        "style": "disney-pixar",
        "aspect_ratio": "16:9",
        "max_scenes": max_scenes,
        "total_scenes": len(scenes),
        "characters": [],
        "visual_contract": {"visual_contract_id": vc_id, "lighting_logic": "", "aspect_ratio": "16:9"},
        "scenes": scenes,
    }


# ─── Mode A — plan → assemble (preferred) ──────────────────────────────────
def _assemble_from_plan(plan: dict, max_scenes: int) -> dict:
    """Wrap assemble_scenes with a real generated_at timestamp."""
    data = assemble_scenes(plan, max_scenes=max_scenes)
    if not data.get("generated_at"):
        data["generated_at"] = datetime.now(timezone.utc).isoformat()
    return data


# ─── Output writers (reused for both modes) ────────────────────────────────
def build_shot_log(data: dict) -> dict:
    """Build the per-shot reproducibility table (report #2 §5)."""
    shots = []
    for scene in data["scenes"]:
        mp = scene.get("motion_params", {})
        shots.append({
            "scene_number": scene["scene_number"],
            "title": scene.get("title", ""),
            "video_prompt": scene["video_prompt"],
            "negative_prompt": scene.get("negative_prompt", ""),
            "aspect_ratio": data["aspect_ratio"],
            "duration_sec": mp.get("duration_sec", 5),
            "fps": scene["motion_params"].get("fps", 24) if "fps" in mp else 24,
            "motion_strength": mp.get("motion_strength", 0.7),
            "seed": scene["seed"],
        })
    return {
        "aspect_ratio": data["aspect_ratio"],
        "resolution": "1920x1080",
        "fps": 24,
        "shots": shots,
    }


def build_prompts_markdown(data: dict) -> str:
    """Human-readable markdown summary."""
    lines = [f"# {data['title']}", "",
             f"*{len(data['scenes'])} scenes · style: {data['style']} · "
             f"aspect ratio: {data['aspect_ratio']}*", ""]

    for scene in data["scenes"]:
        s = scene["scene_number"]
        lines.append(f"## Scene {s}: {scene.get('title', '')}")
        lines.append("")

        if scene.get("narration"):
            lines.append(f"> {scene['narration']}")
            lines.append("")

        if scene.get("dialogue"):
            for d in scene["dialogue"]:
                lines.append(f"**{d.get('speaker', '')}:** \"{d.get('line', '')}\"")
            lines.append("")

        if scene.get("visual_description"):
            lines.append(f"{scene['visual_description']}")
            lines.append("")

        cine = scene.get("cinematography", {})
        if cine:
            lines.append(f"- Camera: {cine.get('camera', '—')}")
            lines.append(f"- Lens: {cine.get('lens', '—')}")
            lines.append(f"- Lighting: {cine.get('lighting', '—')}")
            lines.append(f"- Color palette: {cine.get('color_palette', '—')}")
            lines.append(f"- Composition: {cine.get('composition', '—')}")
            lines.append(f"- Mood: {cine.get('mood', '—')}")
            lines.append("")

        vp = scene.get("video_prompt", "")
        if vp:
            lines.append(f"**Video prompt (5s):** {vp}")
            lines.append("")

        cont = scene.get("continuity", {})
        if cont:
            lines.append(f"- Continuity contract: {cont.get('visual_contract_id', '—')}")
            lines.append(f"- Shot rule: {cont.get('shot_rule', '—')}")
            lines.append(f"- Carried over: {', '.join(cont.get('carried_over', [])) or '—'}")
            lines.append("")

    return "\n".join(lines)


def write_outputs(data: dict, output_dir: Path) -> None:
    """Write scenes.json, shot_log.json and prompts.md into output_dir."""
    slug = _slugify_title(data["title"])
    out_path = output_dir / slug
    out_path.mkdir(parents=True, exist_ok=True)

    (out_path / "scenes.json").write_text(
        json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")

    (out_path / "shot_log.json").write_text(
        json.dumps(build_shot_log(data), indent=2, ensure_ascii=False), encoding="utf-8")

    (out_path / "prompts.md").write_text(build_prompts_markdown(data), encoding="utf-8")


# ─── CLI entry point ───────────────────────────────────────────────────────
def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Offline, language-agnostic scene breakdown and 5-second video-prompt generator.")
    g = p.add_mutually_exclusive_group()
    g.add_argument("--plan", help="Path to a structured plan.json (Mode A — preferred).")
    g.add_argument("--text", help="Direct text input (any language), Mode B.")
    g.add_argument("--file", help="Path to a .txt/.md file with text, Mode B.")
    p.add_argument("--style", default="disney-pixar")
    p.add_argument("--aspect", default="16:9", choices=["16:9", "9:16", "1:1", "4:3"])
    p.add_argument("--max-scenes", type=int, default=12)
    p.add_argument("--output", default="prompts")
    p.add_argument("--force", action="store_true", help="Re-generate if output exists.")
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)

    output_dir = Path(args.output)

    # ── Mode A: structured plan (movie-maker integration) ───────────────
    if args.plan is not None:
        plan_path = Path(args.plan)
        if not plan_path.exists():
            print(f"Error: plan file not found: {plan_path}", file=sys.stderr)
            return 2
        try:
            plan_in = json.loads(plan_path.read_text(encoding="utf-8"))
        except Exception as e:
            print(f"Error: could not parse plan.json: {e}", file=sys.stderr)
            return 2

        try:
            plan = build_plan_from_plot(plan_in)
        except ValueError as e:
            print(f"Error: invalid plan — {e}", file=sys.stderr)
            return 2

        slug = _slugify_title(plan.get("theme", "")[:50]) or "plan_breakdown"
        out_path = output_dir / slug

        if out_path.exists() and not args.force:
            print(f"Output already exists at {out_path}. Use --force to overwrite.")
            return 0

        data = _assemble_from_plan(plan, args.max_scenes)
        write_outputs(data, output_dir)

        print(f"Generated {data['total_scenes']} scene(s).")
        print(f"Theme: {plan.get('theme', '')}")
        for s in data["scenes"]:
            d = [f'{d.get("speaker","")}: "{d.get("line","")[:20]}"'
                 for d in s.get("dialogue", []) if d.get("line")]
            tag = f" [DIALOGUE: {', '.join(d)}]" if d else ""
            print(f"  Scene {s['scene_number']}: '{s.get('title','')}'{tag}")
        print(f"Files written: {out_path}/scenes.json, shot_log.json, prompts.md")
        return 0

    # ── Mode B: plain text (backward compatible) ────────────────────────
    if args.text is not None:
        text = args.text.strip()
    elif args.file is not None:
        try:
            text = Path(args.file).read_text(encoding="utf-8").strip()
        except FileNotFoundError:
            print(f"Error: file not found: {args.file}", file=sys.stderr)
            return 2
    else:
        print("Error: provide --plan <path>, --text, or --file.", file=sys.stderr)
        return 2

    if not text:
        print("Error: empty input.", file=sys.stderr)
        return 2

    out_path = output_dir / _slugify_title(text[:60])
    if out_path.exists() and not args.force:
        print(f"Output already exists at {out_path}. Use --force to overwrite.")
        return 0

    data = _assemble_plain_text(text, args.max_scenes)
    write_outputs(data, output_dir)

    print(f"Generated {data['total_scenes']} scene(s).")
    for s in data["scenes"]:
        print(f"  Scene {s['scene_number']}: {s['title']} "
              f"(mood: {s['cinematography']['mood']})")
    print("Files written: scenes.json, shot_log.json, prompts.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
